version: "3.8"
services:
  postgres-auth:
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
  postgres-products:
    volumes:
      - pg_products_data:/var/lib/postgresql/data
volumes:
  pg_auth_data:
  pg_products_data:
