apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: netabola
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
        - name: loyalty-service
          image: netabola/loyalty-service:latest
          ports:
            - containerPort: 8085
