name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to K8s
        run: |
          kubectl set image deployment/auth-service auth-service=netabola/auth-service:${{ github.sha }}
          kubectl set image deployment/api-gateway api-gateway=netabola/api-gateway:${{ github.sha }}
